### ISSUE TITLE
Documentation could use a pointer to how to install

### ISSUE THREAD

**Issue by pholbrook** [chauncey-garrett/keyboard-maestro-quickcursorkm#1]
I'm not a heavy user of Keyboard Maestro, but I have created a few macros for myself. What I haven't done is install any third party macros. I have no doubt I can figure it out if I poke around, but some brief instructions or a pointer to the same would be useful documentation.

**Comment by chauncey-garrett** [comment]
That would certainly be useful!

I've added an [installation section](https://github.com/chauncey-garrett/keyboard-maestro-quickcursorkm#installation) as well as support for several more editors. Enjoy!
